### ISSUE TITLE
Isn't there a way to package this app?

### ISSUE THREAD

**Issue by super-dev-star516** [Sanan4li/React-Electron-TailwindCSS-Boilerplate#1]
This is awesome boilerplate.
I would like to package this app for Windows, Linux and Mac.
So, I tried to install "electron-packager" but this I got unexpected issue.
![image](https://user-images.githubusercontent.com/107636660/197362766-976062cf-151f-4b22-8c99-555eb14b70b2.png)

Can you help me out please?

**Comment by Sanan4li** [comment]
Hi, This repository is just a fork of https://github.com/alexdevero/electron-react-webpack-boilerplate
You can find ways to package the app. Please check the documentation.
